[theme]
base = "dark"
primaryColor = "#b23a2c"
backgroundColor = "#17324c"
secondaryBackgroundColor = "#ece0bb"
textColor = "#ece0bb"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
